model: &model
  num_classes: 10
  backbone: resnet18
  pretrained: true
  checkpoint_path: ''

train: &train
  num_epochs: 100

  optimizer: &optimizer
    name: sgd
    lr: 0.01
    momentum: 0.9
    nesterov: False
    weight_decay: 0.001

  lr_schedule: &lr_schedule
    name: custom
    milestones: [50, 100]
    gamma: 0.3

eval: &eval
  standard: accuracy

data: &data
  name: 'cifar10'
  root: 'data'
  batch_size: 128
  num_workers: 4

  transform: &transform
    image_size: 32
    crop_size: 28
