model: &model
  num_classes: 200
  backbone: resnet50
  pretrained: true
  avgpool_threshold: 0.0
  checkpoint_path: ''

train: &train
  num_epochs: 100

  optimizer: &optimizer
    name: sgd
    lr: 0.005
    momentum: 0.9
    nesterov: False
    weight_decay: 0.001

  lr_schedule: &lr_schedule
    name: custom
    milestones: [50, 100]
    gamma: 0.3

eval: &eval
  standard: accuracy

data: &data
  name: ''
  root: 'data'
  batch_size: 32
  num_workers: 4

  transform: &transform
    image_size: 256
    crop_size: 224
